---
- name: Install PHP
  apt: name=php5 state=latest

- name: Install PHP GD library
  apt: name=php5-gd state=latest
  notify:
    - Restart Apache

- name: Install PHP Pear
  apt: name=php-pear state=latest
  notify:
    - Restart Apache

- name: Install PHP MySQL
  apt: name=php5-mysql state=latest
  notify:
    - Restart Apache

- name: Install PHP Dev
  apt: name=php5-dev state=latest
  notify:
    - Restart Apache

- name: Install PHP mcrypt
  apt: name=php5-mcrypt state=latest
  notify:
    - Restart Apache

- name: Install PHP redis
  apt: name=php5-redis state=latest
  notify:
    - Restart Apache

- name: Install PHP imap
  apt: name=php5-imap state=latest
  notify:
    - Restart Apache

- name: Install PHP imap
  apt: name=php5-imap state=latest
  notify:
    - Restart Apache

- name: PHP configuring
  shell: "sed -i 's/{{ item.from }}/{{ item.to }}/g' /etc/php5/apache2/php.ini"
  with_items:
    - { from: "display_errors = Off", to: "display_errors = On" }
    - { from: "post_max_size = 8M", to: "post_max_size = 128M" }
    - { from: "upload_max_filesize = 2M", to: "upload_max_filesize = 122M" }
    - { from: "session.gc_maxlifetime = 1440", to: "session.gc_maxlifetime = 86400" }
  notify:
    - Restart Apache

- name: PHP enable mcrypt
  shell: php5enmod mcrypt
