---
- name: Install PHP
  apt: name=php5 state=latest

- name: Install PHP dependencies
  apt: "name={{item}} state=latest"
  with_items:
    - php-pear
    - php5-mysql
    - php5-dev
    - php5-mcrypt
    - php5-redis
    - php5-imap
    - php5-curl
  notify:
    - Restart Apache

- name: PHP configuring
  shell: "sed -i 's/{{ item.from }}/{{ item.to }}/g' /etc/php5/apache2/php.ini"
  with_items:
    - { from: "display_errors = Off", to: "display_errors = On" }
    - { from: "post_max_size = 8M", to: "post_max_size = 128M" }
    - { from: "upload_max_filesize = 2M", to: "upload_max_filesize = 122M" }
    - { from: "session.gc_maxlifetime = 1440", to: "session.gc_maxlifetime = 86400" }
  notify:
    - Restart Apache

- name: PHP enable mcrypt
  shell: php5enmod mcrypt
