---
- hosts: all
  sudo: true
  roles:
    - { role: apt,     tags: ['apt'] }
    - { role: mysql,   tags: ['webserver', 'database', 'mysql'] }
    - { role: sqlite,  tags: ['webserver', 'database', 'sqlite'] }
    - { role: apache,  tags: ['webserver', 'apache', 'php'] }
    - { role: php,     tags: ['webserver', 'php'] }
    - { role: postfix, tags: ['webserver', 'postfix'] }
    - { role: redis,   tags: ['webserver', 'redis'] }
    - { role: common,  tags: ['common'] }
