---
- name: Python 2
  apt: name=python state=latest

- name: Python 2 pip
  apt: name=python-pip state=latest

- name: Python 3
  apt: name=python3 state=latest

- name: Python 3 pip
  apt: name=python3-pip state=latest
