---

- name: Put authorized_key
  authorized_key:
    user: "ubuntu"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  ignore_errors: true

- name: Install Common tools
  apt: "name={{item}} state=latest"
  with_items: "{{common_tools}}"

- name: Put configs
  copy:
    src: configs/
    dest: "{{item.home}}"
    owner: "{{item.owner}}"
    group: "{{item.group}}"
  with_items: "{{common_users}}"

- name: Vim extract
  shell: "tar xzf {{item.home}}/vim.tgz -C {{item.home}} && rm {{item.home}}/vim.tgz"
  with_items: "{{common_users}}"

- name: Vim permissions
  shell: "chown -R {{item.owner}}:{{item.group}} {{item.home}}/.vim"
  with_items: "{{common_users}}"

# - name: Host
#   shell: 'echo "10.0.2.2    {{ hostname }}" >> /etc/hosts'
#   tags: ['post']
