---

- name: Composer exists?
  stat:
    path=/usr/local/bin/composer
  register: COMPOSER_STAT

- name: Put composer
  copy:
    src=composer.phar
    dest=/usr/local/bin/composer
    mode=755
    owner=root
    group=root
  when: (not COMPOSER_STAT.stat.exists)

- name: Composer token root
  shell: "composer config -g github-oauth.github.com {{composer_token}}"
  sudo: true
  when: composer_token != ""

- name: Composer token user
  shell: "composer config -g github-oauth.github.com {{composer_token}}"
  sudo: false
  when: composer_token != ""
