---
- name: Install PHP
  apt: name=php5 state=latest

- name: Install PHP dependencies
  apt: "name={{item}} state=latest"
  with_items: "{{php_modules}}"
  notify:
    - restart apache

- name: PHP configuring
  shell: "sed -i 's/{{ item.from }}/{{ item.to }}/g' /etc/php5/apache2/php.ini"
  with_items: "{{php_config_options}}"
  notify:
    - restart apache

- name: PHP enable modules
  shell: "php5enmod {{item}}"
  with_items: "{{php_enable_modules}}"
  notify:
    - restart apache

- include: composer.yml
