---
php_modules:
  - php-pear
  - php-mysql
  - php-mcrypt
  - php-memcached
  - php-redis
  - php-imap
  - php-curl
  - php-gd
  - php-intl
  - php-mbstring
  - php-bcmath
  - php-soap
  - php-sqlite3
  - php-dev
  - php-xdebug

php_enable_modules:
  - mcrypt
