---
- name: PostgreSQL package
  apt: name={{ item }} state=latest
  with_items:
    - postgresql
    - postgresql-contrib
    - python-psycopg2

- name: PostgreSQL password
  postgresql_user:
    name: postgres
    password: "{{ pgsql_postgres_password }}"
  become: true
  become_user: postgres

# - name: PostgreSQL extra user
#   postgresql_user:
#     name: "{{ pgsql_user }}"
#     password: "{{ pgsql_password }}"
#     role_attr_flags: SUPERUSER,CREATEROLE,CREATEUSER,CREATEDB,LOGIN,REPLICATION
#   become: true
#   become_user: postgres

