---

- name: MySQL Ansible dependencies
  apt: name=python-mysqldb state=latest
  when: ansible_os_family == "Debian"
  tags:
    - mysql
    - install

- name: MySQL server
  apt: name=mysql-server state=latest

- name: MySQL client
  apt: name=mysql-client state=latest

- name: MySQL root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: ""
  ignore_errors: true

- name: MySQL start service
  service: name=mysql state=started

- name: MySQL custom user
  mysql_user:
    host: "%"
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"

- name: MySQL Put .my.cnf
  template:
    src=my.cnf.j2
    dest="{{ item.home }}/.my.cnf"
    owner="{{ item.user }}"
    group="{{ item.group }}"
  with_items:
    - { user: "vagrant", group: "vagrant", home: "/home/vagrant" }
    - { user: "root", group: "root", home: "/root" }

- name: MySQL bind addr
  shell: sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/my.cnf #FIXME
